### ISSUE TITLE
Java EE Enterprise Application Development Tutorial

### ISSUE THREAD

**Issue by hrxiong** [johnnymillergh/JavaWebSSMLearning#1]
can you share more detail about this book. i could't google any book with same name.

**Comment by johnnymillergh** [comment]
Here is a link about the book I read. 
[Java EE企业级应用开发教程（Spring+Spring MVC+MyBatis）](https://www.amazon.cn/dp/B07511FB9J)

**Comment by johnnymillergh** [comment]
[JavaWebSSMLearning](https://github.com/johnnymillergh/JavaWebSSMLearning/) is a very simple tutorial to understand the basic of Spring Framework, not the core. If you’re going to dive into Spring Framework deeper, I highly recommend you to get access to my another Git repository - [SpringBootTemplate](https://github.com/johnnymillergh/SpringBootTemplate), which is under development.
Feel free to clone it. 😄
